language: Java
services:
- docker

script:
- echo -e "travis_fold:start:Geppetto-Config"
- export VFB_REPO=$(echo ${TRAVIS_REPO_SLUG##*/} | awk '{gsub(/\-/,"_",$0);gsub(/\./,"_",$0);print toupper($0)}')
- export REPO=$(echo ${TRAVIS_REPO_SLUG} | awk '{gsub(/\./,"_",$0);print tolower($0)}')
- export TAG=`if [ "$TRAVIS_BRANCH" == "docker-server" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- echo -e "travis_fold:end:Geppetto-Config"
- echo -e "travis_fold:start:Docker-Build"
- docker build -t $REPO:$COMMIT .
- echo -e "travis_fold:end:Docker-Build"

after_success:
- cd $TRAVIS_BUILD_DIR
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push $REPO:$TAG
