<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%><%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%><?xml version="1.0" encoding="UTF-8"?>
<tns:geppettoModel
    xmlns:tns="http://www.openworm.org/simulationSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openworm.org/simulationSchema ../../main/resources/schema/simulation/simulationSchema.xsd">
    <tns:entity>
        <tns:id>flybrain</tns:id>
        <tns:aspect>
            <tns:id>morphology</tns:id>
        </tns:aspect>
        <tns:entity>
            <tns:id>regions</tns:id>
            <tns:aspect>
                <tns:id>morphology</tns:id>
            </tns:aspect>
            <tns:entity>
                <tns:id>AL_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/AL_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>AL_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/AL_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>AME_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/AME_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>AME_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/AME_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>AMMC_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/AMMC_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>AMMC_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/AMMC_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>AOTU_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/AOTU_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>AOTU_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/AOTU_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>ATL_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/ATL_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>ATL_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/ATL_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>AVLP_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/AVLP_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>AVLP_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/AVLP_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>BU_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/BU_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>BU_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/BU_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>CAN_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/CAN_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>CAN_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/CAN_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>CRE_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/CRE_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>CRE_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/CRE_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>EB</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/EB.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>EPA_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/EPA_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>EPA_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/EPA_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>FB</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/FB.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>FLA_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/FLA_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>FLA_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/FLA_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>GA_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/GA_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>GA_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/GA_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>GNG</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/GNG.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>GOR_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/GOR_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>GOR_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/GOR_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>IB_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/IB_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>IB_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/IB_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>ICL_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/ICL_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>ICL_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/ICL_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>IPS_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/IPS_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>IPS_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/IPS_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>IVLP_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/IVLP_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>IVLP_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/IVLP_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>LAL_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/LAL_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>LAL_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/LAL_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>LH_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/LH_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>LH_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/LH_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>LO_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/LO_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>LO_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/LO_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>LOP_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/LOP_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>LOP_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/LOP_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>MB_CA_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/MB_CA_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>MB_CA_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/MB_CA_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>MB_ML_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/MB_ML_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>MB_ML_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/MB_ML_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>MB_PED_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/MB_PED_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>MB_PED_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/MB_PED_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>MB_VL_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/MB_VL_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>MB_VL_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/MB_VL_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>ME_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/ME_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>ME_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/ME_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>NO</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/NO.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>PB</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/PB.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>PLP_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/PLP_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>PLP_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/PLP_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>PRW</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/PRW.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>PVLP_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/PVLP_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>PVLP_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/PVLP_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>SAD</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/SAD.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>SCL_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/SCL_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>SCL_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/SCL_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>SIP_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/SIP_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>SIP_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/SIP_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>SLP_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/SLP_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>SLP_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/SLP_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>SMP_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/SMP_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>SMP_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/SMP_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>SPS_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/SPS_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>SPS_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/SPS_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>VES_L</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/VES_L.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
            <tns:entity>
                <tns:id>VES_R</tns:id>
                <tns:aspect>
                    <tns:id>morphology</tns:id>
                    <tns:model>
                        <tns:modelInterpreterId>objModelInterpreterService</tns:modelInterpreterId>
                        <tns:modelURL>SERVER_ROOT/appdata/vfb/brain/obj/VES_R.obj</tns:modelURL>
                    </tns:model>
                </tns:aspect>
            </tns:entity>
        </tns:entity>
        <tns:entity>
            <tns:id>neurons</tns:id>
            <tns:aspect>
                <tns:id>morphology</tns:id>
            </tns:aspect><c:if test="${fn:length(indxml)>0}">${indxml}</c:if>
        </tns:entity>
    </tns:entity>
</tns:geppettoModel>
