s/\/usr\/local\/tomcat-6\/webapps\/vfbdev\//\/usr\/local\/tomcat-6\/webapps\/WEBAPP_NAME\//g
s/\/usr\/local\/tomcat-6\/webapps\/vfbsb\//\/usr\/local\/tomcat-6\/webapps\/WEBAPP_NAME\//g
s/\/usr\/local\/tomcat-6\/webapps\/GITvfb\//\/usr\/local\/tomcat-6\/webapps\/WEBAPP_NAME\//g
s/\/usr\/local\/tomcat-6\/webapps\/vfb\//\/usr\/local\/tomcat-6\/webapps\/WEBAPP_NAME\//g
s/vfbdev.inf.ed.ac.uk/www.virtualflybrain.org/g
s/vfbsb.inf.ed.ac.uk/www.virtualflybrain.org/g
s/vfb-karenin.inf.ed.ac.uk/www.virtualflybrain.org/g
s/vfb-blanik.inf.ed.ac.uk/www.virtualflybrain.org/g
s/vfb-bocian.inf.ed.ac.uk/www.virtualflybrain.org/g
